// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Member.proto

package groupservice;

public final class GossipProto {
  private GossipProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MemberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.joyboys.Member)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>optional string ip = 2;</code>
     * @return Whether the ip field is set.
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 2;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 2;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional int32 port = 3;</code>
     * @return Whether the port field is set.
     */
    boolean hasPort();
    /**
     * <code>optional int32 port = 3;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>optional string name = 4;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 4;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 4;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.joyboys.Member}
   */
  public static final class Member extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.joyboys.Member)
      MemberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Member.newBuilder() to construct.
    private Member(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Member() {
      ip_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Member();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return groupservice.GossipProto.internal_static_com_joyboys_Member_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return groupservice.GossipProto.internal_static_com_joyboys_Member_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              groupservice.GossipProto.Member.class, groupservice.GossipProto.Member.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_ = 0L;
    /**
     * <code>optional int64 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int IP_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ip_ = "";
    /**
     * <code>optional string ip = 2;</code>
     * @return Whether the ip field is set.
     */
    @java.lang.Override
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string ip = 2;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 2;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_ = 0;
    /**
     * <code>optional int32 port = 3;</code>
     * @return Whether the port field is set.
     */
    @java.lang.Override
    public boolean hasPort() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 port = 3;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>optional string name = 4;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string name = 4;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 4;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, port_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof groupservice.GossipProto.Member)) {
        return super.equals(obj);
      }
      groupservice.GossipProto.Member other = (groupservice.GossipProto.Member) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasIp() != other.hasIp()) return false;
      if (hasIp()) {
        if (!getIp()
            .equals(other.getIp())) return false;
      }
      if (hasPort() != other.hasPort()) return false;
      if (hasPort()) {
        if (getPort()
            != other.getPort()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static groupservice.GossipProto.Member parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static groupservice.GossipProto.Member parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static groupservice.GossipProto.Member parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static groupservice.GossipProto.Member parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static groupservice.GossipProto.Member parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static groupservice.GossipProto.Member parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static groupservice.GossipProto.Member parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static groupservice.GossipProto.Member parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static groupservice.GossipProto.Member parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static groupservice.GossipProto.Member parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static groupservice.GossipProto.Member parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static groupservice.GossipProto.Member parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(groupservice.GossipProto.Member prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.joyboys.Member}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.joyboys.Member)
        groupservice.GossipProto.MemberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return groupservice.GossipProto.internal_static_com_joyboys_Member_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return groupservice.GossipProto.internal_static_com_joyboys_Member_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                groupservice.GossipProto.Member.class, groupservice.GossipProto.Member.Builder.class);
      }

      // Construct using groupservice.GossipProto.Member.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0L;
        ip_ = "";
        port_ = 0;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return groupservice.GossipProto.internal_static_com_joyboys_Member_descriptor;
      }

      @java.lang.Override
      public groupservice.GossipProto.Member getDefaultInstanceForType() {
        return groupservice.GossipProto.Member.getDefaultInstance();
      }

      @java.lang.Override
      public groupservice.GossipProto.Member build() {
        groupservice.GossipProto.Member result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public groupservice.GossipProto.Member buildPartial() {
        groupservice.GossipProto.Member result = new groupservice.GossipProto.Member(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(groupservice.GossipProto.Member result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ip_ = ip_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.port_ = port_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.name_ = name_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof groupservice.GossipProto.Member) {
          return mergeFrom((groupservice.GossipProto.Member)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(groupservice.GossipProto.Member other) {
        if (other == groupservice.GossipProto.Member.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasIp()) {
          ip_ = other.ip_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasName()) {
          name_ = other.name_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                ip_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                port_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 2;</code>
       * @return Whether the ip field is set.
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string ip = 2;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 2;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 2;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ip_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        ip_ = getDefaultInstance().getIp();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 2;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ip_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>optional int32 port = 3;</code>
       * @return Whether the port field is set.
       */
      @java.lang.Override
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 port = 3;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 3;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 4;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string name = 4;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.joyboys.Member)
    }

    // @@protoc_insertion_point(class_scope:com.joyboys.Member)
    private static final groupservice.GossipProto.Member DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new groupservice.GossipProto.Member();
    }

    public static groupservice.GossipProto.Member getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Member>
        PARSER = new com.google.protobuf.AbstractParser<Member>() {
      @java.lang.Override
      public Member parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Member> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Member> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public groupservice.GossipProto.Member getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MemberListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.joyboys.MemberList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    java.util.List<groupservice.GossipProto.Member> 
        getMemberListList();
    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    groupservice.GossipProto.Member getMemberList(int index);
    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    int getMemberListCount();
    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    java.util.List<? extends groupservice.GossipProto.MemberOrBuilder> 
        getMemberListOrBuilderList();
    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    groupservice.GossipProto.MemberOrBuilder getMemberListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.joyboys.MemberList}
   */
  public static final class MemberList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.joyboys.MemberList)
      MemberListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MemberList.newBuilder() to construct.
    private MemberList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MemberList() {
      memberList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MemberList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return groupservice.GossipProto.internal_static_com_joyboys_MemberList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return groupservice.GossipProto.internal_static_com_joyboys_MemberList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              groupservice.GossipProto.MemberList.class, groupservice.GossipProto.MemberList.Builder.class);
    }

    public static final int MEMBERLIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<groupservice.GossipProto.Member> memberList_;
    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<groupservice.GossipProto.Member> getMemberListList() {
      return memberList_;
    }
    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends groupservice.GossipProto.MemberOrBuilder> 
        getMemberListOrBuilderList() {
      return memberList_;
    }
    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    @java.lang.Override
    public int getMemberListCount() {
      return memberList_.size();
    }
    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    @java.lang.Override
    public groupservice.GossipProto.Member getMemberList(int index) {
      return memberList_.get(index);
    }
    /**
     * <code>repeated .com.joyboys.Member memberList = 1;</code>
     */
    @java.lang.Override
    public groupservice.GossipProto.MemberOrBuilder getMemberListOrBuilder(
        int index) {
      return memberList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < memberList_.size(); i++) {
        output.writeMessage(1, memberList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < memberList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, memberList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof groupservice.GossipProto.MemberList)) {
        return super.equals(obj);
      }
      groupservice.GossipProto.MemberList other = (groupservice.GossipProto.MemberList) obj;

      if (!getMemberListList()
          .equals(other.getMemberListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMemberListCount() > 0) {
        hash = (37 * hash) + MEMBERLIST_FIELD_NUMBER;
        hash = (53 * hash) + getMemberListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static groupservice.GossipProto.MemberList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static groupservice.GossipProto.MemberList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static groupservice.GossipProto.MemberList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static groupservice.GossipProto.MemberList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static groupservice.GossipProto.MemberList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static groupservice.GossipProto.MemberList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static groupservice.GossipProto.MemberList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static groupservice.GossipProto.MemberList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static groupservice.GossipProto.MemberList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static groupservice.GossipProto.MemberList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static groupservice.GossipProto.MemberList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static groupservice.GossipProto.MemberList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(groupservice.GossipProto.MemberList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.joyboys.MemberList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.joyboys.MemberList)
        groupservice.GossipProto.MemberListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return groupservice.GossipProto.internal_static_com_joyboys_MemberList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return groupservice.GossipProto.internal_static_com_joyboys_MemberList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                groupservice.GossipProto.MemberList.class, groupservice.GossipProto.MemberList.Builder.class);
      }

      // Construct using groupservice.GossipProto.MemberList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (memberListBuilder_ == null) {
          memberList_ = java.util.Collections.emptyList();
        } else {
          memberList_ = null;
          memberListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return groupservice.GossipProto.internal_static_com_joyboys_MemberList_descriptor;
      }

      @java.lang.Override
      public groupservice.GossipProto.MemberList getDefaultInstanceForType() {
        return groupservice.GossipProto.MemberList.getDefaultInstance();
      }

      @java.lang.Override
      public groupservice.GossipProto.MemberList build() {
        groupservice.GossipProto.MemberList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public groupservice.GossipProto.MemberList buildPartial() {
        groupservice.GossipProto.MemberList result = new groupservice.GossipProto.MemberList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(groupservice.GossipProto.MemberList result) {
        if (memberListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            memberList_ = java.util.Collections.unmodifiableList(memberList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.memberList_ = memberList_;
        } else {
          result.memberList_ = memberListBuilder_.build();
        }
      }

      private void buildPartial0(groupservice.GossipProto.MemberList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof groupservice.GossipProto.MemberList) {
          return mergeFrom((groupservice.GossipProto.MemberList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(groupservice.GossipProto.MemberList other) {
        if (other == groupservice.GossipProto.MemberList.getDefaultInstance()) return this;
        if (memberListBuilder_ == null) {
          if (!other.memberList_.isEmpty()) {
            if (memberList_.isEmpty()) {
              memberList_ = other.memberList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMemberListIsMutable();
              memberList_.addAll(other.memberList_);
            }
            onChanged();
          }
        } else {
          if (!other.memberList_.isEmpty()) {
            if (memberListBuilder_.isEmpty()) {
              memberListBuilder_.dispose();
              memberListBuilder_ = null;
              memberList_ = other.memberList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              memberListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMemberListFieldBuilder() : null;
            } else {
              memberListBuilder_.addAllMessages(other.memberList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                groupservice.GossipProto.Member m =
                    input.readMessage(
                        groupservice.GossipProto.Member.parser(),
                        extensionRegistry);
                if (memberListBuilder_ == null) {
                  ensureMemberListIsMutable();
                  memberList_.add(m);
                } else {
                  memberListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<groupservice.GossipProto.Member> memberList_ =
        java.util.Collections.emptyList();
      private void ensureMemberListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          memberList_ = new java.util.ArrayList<groupservice.GossipProto.Member>(memberList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          groupservice.GossipProto.Member, groupservice.GossipProto.Member.Builder, groupservice.GossipProto.MemberOrBuilder> memberListBuilder_;

      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public java.util.List<groupservice.GossipProto.Member> getMemberListList() {
        if (memberListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(memberList_);
        } else {
          return memberListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public int getMemberListCount() {
        if (memberListBuilder_ == null) {
          return memberList_.size();
        } else {
          return memberListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public groupservice.GossipProto.Member getMemberList(int index) {
        if (memberListBuilder_ == null) {
          return memberList_.get(index);
        } else {
          return memberListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public Builder setMemberList(
          int index, groupservice.GossipProto.Member value) {
        if (memberListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMemberListIsMutable();
          memberList_.set(index, value);
          onChanged();
        } else {
          memberListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public Builder setMemberList(
          int index, groupservice.GossipProto.Member.Builder builderForValue) {
        if (memberListBuilder_ == null) {
          ensureMemberListIsMutable();
          memberList_.set(index, builderForValue.build());
          onChanged();
        } else {
          memberListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public Builder addMemberList(groupservice.GossipProto.Member value) {
        if (memberListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMemberListIsMutable();
          memberList_.add(value);
          onChanged();
        } else {
          memberListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public Builder addMemberList(
          int index, groupservice.GossipProto.Member value) {
        if (memberListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMemberListIsMutable();
          memberList_.add(index, value);
          onChanged();
        } else {
          memberListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public Builder addMemberList(
          groupservice.GossipProto.Member.Builder builderForValue) {
        if (memberListBuilder_ == null) {
          ensureMemberListIsMutable();
          memberList_.add(builderForValue.build());
          onChanged();
        } else {
          memberListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public Builder addMemberList(
          int index, groupservice.GossipProto.Member.Builder builderForValue) {
        if (memberListBuilder_ == null) {
          ensureMemberListIsMutable();
          memberList_.add(index, builderForValue.build());
          onChanged();
        } else {
          memberListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public Builder addAllMemberList(
          java.lang.Iterable<? extends groupservice.GossipProto.Member> values) {
        if (memberListBuilder_ == null) {
          ensureMemberListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, memberList_);
          onChanged();
        } else {
          memberListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public Builder clearMemberList() {
        if (memberListBuilder_ == null) {
          memberList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          memberListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public Builder removeMemberList(int index) {
        if (memberListBuilder_ == null) {
          ensureMemberListIsMutable();
          memberList_.remove(index);
          onChanged();
        } else {
          memberListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public groupservice.GossipProto.Member.Builder getMemberListBuilder(
          int index) {
        return getMemberListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public groupservice.GossipProto.MemberOrBuilder getMemberListOrBuilder(
          int index) {
        if (memberListBuilder_ == null) {
          return memberList_.get(index);  } else {
          return memberListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public java.util.List<? extends groupservice.GossipProto.MemberOrBuilder> 
           getMemberListOrBuilderList() {
        if (memberListBuilder_ != null) {
          return memberListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(memberList_);
        }
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public groupservice.GossipProto.Member.Builder addMemberListBuilder() {
        return getMemberListFieldBuilder().addBuilder(
            groupservice.GossipProto.Member.getDefaultInstance());
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public groupservice.GossipProto.Member.Builder addMemberListBuilder(
          int index) {
        return getMemberListFieldBuilder().addBuilder(
            index, groupservice.GossipProto.Member.getDefaultInstance());
      }
      /**
       * <code>repeated .com.joyboys.Member memberList = 1;</code>
       */
      public java.util.List<groupservice.GossipProto.Member.Builder> 
           getMemberListBuilderList() {
        return getMemberListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          groupservice.GossipProto.Member, groupservice.GossipProto.Member.Builder, groupservice.GossipProto.MemberOrBuilder> 
          getMemberListFieldBuilder() {
        if (memberListBuilder_ == null) {
          memberListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              groupservice.GossipProto.Member, groupservice.GossipProto.Member.Builder, groupservice.GossipProto.MemberOrBuilder>(
                  memberList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          memberList_ = null;
        }
        return memberListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.joyboys.MemberList)
    }

    // @@protoc_insertion_point(class_scope:com.joyboys.MemberList)
    private static final groupservice.GossipProto.MemberList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new groupservice.GossipProto.MemberList();
    }

    public static groupservice.GossipProto.MemberList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MemberList>
        PARSER = new com.google.protobuf.AbstractParser<MemberList>() {
      @java.lang.Override
      public MemberList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MemberList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MemberList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public groupservice.GossipProto.MemberList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_joyboys_Member_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_joyboys_Member_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_joyboys_MemberList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_joyboys_MemberList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Member.proto\022\013com.joyboys\"~\n\006Member\022\026\n" +
      "\ttimestamp\030\001 \001(\003H\000\210\001\001\022\017\n\002ip\030\002 \001(\tH\001\210\001\001\022\021" +
      "\n\004port\030\003 \001(\005H\002\210\001\001\022\021\n\004name\030\004 \001(\tH\003\210\001\001B\014\n\n" +
      "_timestampB\005\n\003_ipB\007\n\005_portB\007\n\005_name\"5\n\nM" +
      "emberList\022\'\n\nmemberList\030\001 \003(\0132\023.com.joyb" +
      "oys.MemberB\035\n\014groupserviceB\013GossipProtoP" +
      "\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_joyboys_Member_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_joyboys_Member_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_joyboys_Member_descriptor,
        new java.lang.String[] { "Timestamp", "Ip", "Port", "Name", "Timestamp", "Ip", "Port", "Name", });
    internal_static_com_joyboys_MemberList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_joyboys_MemberList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_joyboys_MemberList_descriptor,
        new java.lang.String[] { "MemberList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
